{% set name = "Augmentor" %}
{% set version = "0.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Augmentor-{{ version }}.tar.gz
  sha256: 1198672f1ab9f97f1e1802803b9165ccb4830e30f8b5f324a7bb2f8f38331d1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pillow >=5.2.0
    - tqdm >=4.9.0
    - numpy >=1.11.0

test:
  imports:
    - Augmentor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mdbloice/Augmentor
  summary: Image augmentation library for Machine Learning
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - claydugo
